const GET_RECIPES = "GET_RECIPES";
const GET_DIETS = "GET_DIETS";
const FILTER_DIETS = "FILTER_DIETS";
const FILTER_HEALTHSCORE = "FILTER_HEALTHSCORE";
const FILTER_ALPHABETICAL = "FILTER_ALPHABETICAL";

export {
  GET_RECIPES,
  GET_DIETS,
  FILTER_DIETS,
  FILTER_HEALTHSCORE,
  FILTER_ALPHABETICAL,
};
