const GET_RECIPES = "GET_RECIPES";
const GET_DETAIL = "GET_DETAIL";
const GET_DIETS = "GET_DIETS";
const GET_RECIPES_CREATED = "GET_RECIPES_CREATED";
const FILTER_DIETS = "FILTER_DIETS";
const FILTER_HEALTHSCORE = "FILTER_HEALTHSCORE";
const FILTER_ALPHABETICAL = "FILTER_ALPHABETICAL";

export {
  GET_RECIPES,
  GET_DETAIL,
  GET_DIETS,
  GET_RECIPES_CREATED,
  FILTER_DIETS,
  FILTER_HEALTHSCORE,
  FILTER_ALPHABETICAL,
};
